### ISSUE TITLE
Enable/Disable Camera

### ISSUE THREAD

**Issue by A-random-githuber** [notmee1/ArcaeaModder#1]
Hi, when i load the libcocos2dcpp.so to turn off the camera movement, after that i replace it with the modified one in the apk. I tried to play an april fools song, it still have the camera movement. Do you have any idea why?

**Comment by notmee1** [comment]
hmm can you try to use original libcocos2dcpp with arcaeamodder and disable all the tick, to see if the camera works? After that if it doesn't works, try to use arcaeamodder to enable the camera and then disable it again to see if it's still happened

**Comment by notmee1** [comment]
anyways, which side of it (Android or iOS)

**Comment by A-random-githuber** [comment]
I dont have a fresh libcocos2dcpp.so :/
I don't know if the Ios side have it since i mainly on Android side.

**Comment by A-random-githuber** [comment]
Ok so, i just try another chart with a green arc in it. It doesn't show the green arc, instead it show the red arc. It's my mistake. Sorry the inconvenience!
